### ISSUE TITLE
A callback was made on a garbage collected delegate

### ISSUE THREAD

**Issue by shodo** [HakanL/DinkToPdf#1]
Hi, 
I'm using your version and it works great apart from the exception above. I've seen that user rdnr0 has made a branch with a fix for that:

https://github.com/rndusr0/DinkToPdf/commit/a2f8e8e9c74cb953b7c62e4e94c424ba048eb2d3

Is it possibile to merge the fix? 
Thanks!

**Comment by HakanL** [comment]
I never tested the callbacks since I don't use that in my application, but I have applied the patch from rndusr0 and uploaded version 1.1.1 to NuGet. Please let me know if that fixed the issue.

**Comment by shodo** [comment]
I'm not using callback neither, but it's a bug of the internal implementation of the original version of Dink2Pdf. I let you know for sure, thanks a lot!

**Comment by shodo** [comment]
Hi hakanL, I've used it for a while, seems it's solved now!

**Comment by HakanL** [comment]
Thanks for reporting back @shodo!
