### ISSUE TITLE
Is this library still alive?

### ISSUE THREAD

**Issue by JavierOlazaran** [HakanL/DinkToPdf#13]
Is the library being maintained?

**Comment by HakanL** [comment]
Yes, but not a lot of changes are planned. Anything you need help with?

**Comment by JavierOlazaran** [comment]
I'm closing the Issue

**Comment by HakanL** [comment]
Yea it's a reasonable question to ask. I use this library for two production (but low volume) projects. The underlying library wkhtmltox is a mature library though.
