### ISSUE TITLE
Fonts not working on server (works locally) even though PDF is being created

### ISSUE THREAD

**Issue by markmcgookin** [HakanL/DinkToPdf#7]
I've managed to get DinkToPdf generating pdfs locally (using DI in an Azure webjob), on a windows machine, and in a cloud app.

However, I reference a font (Swis721 Th BT) in my markup that isn't installed on any of these machines, so I use @font-face to add support for it. This works great on Mac, on Windows machine, but just doesn't work on the Cloud app (although the PDF is still generated)

I have tried:

1. - 'link' style sheet with font file references
2. - 'link' style sheet with embedded ttf fonts
3. - <style> tags with font file references
4. - <style> tags with embedded base64 ttf font
5. - <style> tags with embedded base64 WOFF font
6. - WebSettings.UserStyleSheet with embedded WOFF font

ALL of these work as markup, and on my local machine and on my windows dev machine as generated PDFs with the new font. But the new font is NEVER rendered in the webjob output.

Can anyone give me ANYTHING else to try?

If I remove the style locally from the markup, the font isn't rendered, so it's not installed on either of my local machines (i've checked)

I've got everything working except this one issue.

**Comment by HakanL** [comment]
Hey Mark, it sounds like this is an issue with the underlying wkhtmltopdf library, the DinkToPdf is just a wrapper around it. I think your best bet is to try the wkhtmltopdf library directly on the affected system to see if you can reproduce it and go from there.

**Comment by MDzyga** [comment]
I have the same problem and tried to use fonts from google fonts website like here: https://stackoverflow.com/questions/10611828/use-custom-fonts-with-wkhtmltopdf.
Locally it works, but after deploy on Azure App Service doesn't work.

**Comment by markmcgookin** [comment]
So I've discussed this with Microsoft over on MSDN and they had asked me to try a few things that I had already tried. None of which worked. It's still unclear whether this is an IIS issue or some web.config setting that we have no control over when deploying to Azure. It's not an issue with dink or wkhtmltopdf, it's an issue with the deployment to azure.

My solution was to quickly dump my webjob into a docker container, where I have full control over the environment... get my code up and running there and working locally. Then I deployed that to a kubernetes cluster in azure (a bit overkill, but apparently the container instance is obsolete and being phased out)... configuring k8s was by far the hardest bit, but I now have it up and running, because of the nature of containered apps I've got a bunch of replicas which will help with performance and I have full control over the fonts etc too. Just don't forget that you will need to add the ".so" library as well as the dll/dylib if you are running on linux.

**Comment by MDzyga** [comment]
Could you give me a link to this discussion on MSDN?

**Comment by markmcgookin** [comment]
> Could you give me a link to this discussion on MSDN?

It's not much help, but have a read [here](https://social.msdn.microsoft.com/Forums/en-US/0fa28cb4-12e6-48bc-a89e-3aa61a46a0d1/how-to-install-a-custom-font-on-an-azure-webapp-for-use-by-a-webjob?forum=windowsazurewebsitespreview&prof=required). 

I would recommend docker if you can to give you more control.
